### ISSUE TITLE
Can't sync or build project

### ISSUE THREAD

**Issue by ajans** [Astroa7m/RemoteWidget#1]
Project-build `./gradlew clean assembleDebug` failed with the following output:

```
> Configure project :app
Evaluating project ':app' using build file '/home/aj/GIT/private/RemoteWidget/app/build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/aj/GIT/private/RemoteWidget/app/build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':app'.
> Parameter specified as non-null is null: method com.android.build.gradle.internal.dsl.BaseFlavor.buildConfigField, parameter value

```

Also, in Android Studio, the gradle-editor could not resolve the symbols `Properties` and `FileInputStream`.
Other projects in Android Studio work fine.

Do you know what could be the issue here? I am using Android Studio stable:

```
Android Studio Chipmunk | 2021.2.1 Patch 2
Build #AI-212.5712.43.2112.8815526, built on July 10, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-46-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.wakatime.intellij.plugin (14.1.0), org.jetbrains.kotlin (212-1.7.10-release-333-AS5457.46), com.nbadal.ktlint (0.10.0), io.sympli.idea.plugin (1.3.8), com.developerphil.adbidea (1.6.6)
Current Desktop: ubuntu:GNOME
```

**Comment by Astroa7m** [comment]
1.  close the project
2. delete the .idea file
3.  add default value in place of null value  in line 26 like so`defaultConfig {
        buildConfigField "String", "CLIENT_ID", localProperties["CLIENT_ID"] ?: ""
    }`

It should work.

**Comment by Astroa7m** [comment]
You should grab an API key from [UnSplash API](https://unsplash.com/developers) and then place it in your `local.properties` file like so
 
`CLIENT_ID = "your_api_key"`
